apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: buildkite

commonLabels:
  service: buildkite

bases:
  - ../../buildkite

secretGenerator:
  - name: buildkite-agent-token
    literals:
      - token=BUILDKITE_AGENT_TOKEN
  - name: buildkite-secrets
    files:
      - ./git-credentials
      - ./private-ssh-key
