steps:
  - label: ":lint-roller: lint"
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: lint
                image: golang:latest
                command: [.buildkite/steps/lint.sh]
                resources:
                  requests:
                    cpu: 1000m
                    memory: 512Mi

  - label: ":docker: build agent"
    key: agent
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: docker
            containers:
              - name: docker
                image: crazymax/docker:latest
                command: [.buildkite/steps/agent.sh]

  - label: ":buildkite: integration tests"
    key: integration
    depends_on: agent
    agents:
      queue: kubernetes
    artifact_paths: junit-*.xml
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: integration-tests
            volumes:
            - name: agent-stack-k8s-config
              configMap:
                name: agent-stack-k8s-config
            containers:
              - name: tests
                image: golang:latest
                command: [.buildkite/steps/tests.sh]
                env:
                - name: CONFIG
                  value: /etc/config.yaml
                envFrom:
                - secretRef:
                    name: agent-stack-k8s-secrets
                volumeMounts:
                - mountPath: /etc/config.yaml
                  name: agent-stack-k8s-config
                  subPath: config.yaml
                resources:
                  requests:
                    cpu: 1000m
                    memory: 512Mi
      - test-collector:
          files: "junit-*.xml"
          format: "junit"

  - label: "publish and deploy"
    if: "build.branch == pipeline.default_branch"
    depends_on:
    - agent
    - integration
    agents:
      queue: kubernetes
    env:
      BUILDKITE_SHELL: /bin/sh -e -c
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: deploy
                image: alpine:latest
                command: [.buildkite/steps/deploy.sh]
                envFrom:
                - secretRef:
                    name: agent-stack-k8s-secrets
