apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integration-tests
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integration-tests
  namespace: buildkite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: integration-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: integration-tests
subjects:
- kind: ServiceAccount
  name: integration-tests
  namespace: buildkite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: docker
  namespace: buildkite
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker
  namespace: buildkite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: docker
  namespace: buildkite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: docker
subjects:
- kind: ServiceAccount
  name: docker
  namespace: buildkite
