apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: integration-tests
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integration-tests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: integration-tests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: integration-tests
subjects:
- kind: ServiceAccount
  name: integration-tests
