apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildkite-controller
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - watch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buildkite-controller
  namespace: buildkite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: buildkite-controller
subjects:
- kind: ServiceAccount
  name: buildkite-controller
  namespace: buildkite
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildkite-controller
  namespace: buildkite
