agent-token-secret: my-kubernetes-secret
debug: true
image: my.registry.dev/buildkite-agent:latest
job-ttl: 5m
max-in-flight: 100
namespace: my-buildkite-ns
org: my-buildkite-org

# only set cluster-uuid if the pipelines are in a cluster
# the UUID may be found in the cluster settings
cluster-uuid: beefcafe-abbe-baba-abba-deedcedecade

tags:
  - queue=my-queue
  - priority=high

# ssh-credentials-secret are the secret with the ssh credentials
# configured on the agent with docker-ssh-config
# @see https://github.com/buildkite/docker-ssh-env-config
ssh-credentials-secret: buildkite-ssh-github-creds


# This will be applied to the job's podSpec as a strategic merge patch
# See https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch
pod-spec-patch:
  serviceAccountName: buildkite-agent-sa
  automountServiceAccountToken: true
  containers:
  - name: container-0
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-secrets
          key: github-token
    resources:
      requests:
        cpu: 100m
        mem: 50Mi
      limits:
        mem: 1Gi
